# make sh file for copying and analyzing data
import os
import stat

filename = "scripts.sh"

transfer_set = 2

if transfer_set == 1:
	template_num = 11
	test_num = 20
	date = "2007-03-27-1"
	movie_spec = "/snle/acquisition/movie-xml/RGB-8-8-0.48-22222.xml"
	movie_spec_test = "/snle/acquisition/movie-xml/RGB-8-8-0.48-33333.xml"
elif transfer_set == 2:
	template_num = 1
	test_num = 12
	date = "2007-08-24-4"
	movie_spec = "/snle/acquisition/movie-xml/RGB-10-8-0.48-11111.xml"
	movie_spec_test = "/snle/acquisition/movie-xml/RGB-10-8-0.48-11111.xml"
	movie_spec_test2 = "snle/acquisition/movie-xml/RGB-10-8-0.48-22222.xml"
elif transfer_set == 3:
	templates = '1, 12, 13'
	movie_specs = ["/snle/acquisition/movie-xml/RGB-10-8-0.48-11111.xml", "/snle/acquisition/movie-xml/RGB-10-8-0.48-11111.xml", "snle/acquisition/movie-xml/RGB-10-8-0.48-22222.xml"
	mapped = '2-12, 14'
	date = "2007-08-24-4"
	
remote_dir = "/rush/snlearchive/data/" + date + "/data%03d/*.bin"
local_data_dir = "/Data/" + date + "/data%03d"

def mkdir(path):
	if not os.path.isdir(path):
		f.write("mkdir %s\n" % path)

def is_empty_folder(path):
	return not os.path.isdir(path) or len(os.listdir(path)) == 0

def rsync(data_num):
	f.write("rsync -a -E -progress " + remote_dir % (data_num,) + " " + local_data_dir % (data_num,) +"\n")
	f.write("echo 'data set %d synced'\n\n" % data_num)
	
class interpret_range:
	def __init__(self, str_range):
		str_range = ''.join(str_range.split())
		self.lst_range = str_range.split(',')
		self.tstart = None
		self.tend = None
	def __iter__(self):
		return self
	def next(self):
		if self.tstart is None and self.tend is None:
			if not self.lst_range :
				raise StopIteration
			else:
				value = self.lst_range.pop(0)
				match = re.match('[0-9]+\-[0-9]+',value)
				if match:
					start_str, end_str = value.split('-')
					self.tstart = int(start_str)
					self.tend = int(end_str)
					assert self.tstart < self.tend
				else:
					return int(value)
		value = self.tstart
		if value >= self.tend:
			self.tstart = None
			self.tend = None
		else:
			self.tstart += 1
		return value


f = open(filename, 'w')

f.write('#!/bin/bash\n')
f.write('# this file was automatically generated by scriptmake.py\n\n\n')

mkdir("/Data/%s" % date)

nwpca_dir = local_data_dir % (template_num,) +"-nwpca"
mkdir(nwpca_dir)
if is_empty_folder(nwpca_dir):
	rsync(template_num)
	f.write("vision-auto-sta-64 " + local_data_dir % (template_num,) + " " + nwpca_dir + " " + movie_spec + " true true\n")
	f.write("echo 'template analyzed'\n\n")

# sync test folder

for i in range(template_num+1, test_num):
	mapped_path = local_data_dir % (i,) + "-from-data%03d-nwpca" % (template_num,)
	mkdir(mapped_path)
	if is_empty_folder(mapped_path):
		if not os.path.isdir(local_data_dir % (i,)):
			f.write("mkdir " + local_data_dir % (i,) + "\n")
		rsync(i)
		f.write("map-auto " + local_data_dir % (i,) + " " + local_data_dir % (template_num,) + "-nwpca " + mapped_path + " ei\n")
		f.write("echo 'data set %d mapped'\n\n" % (i,))

nwpca_dir_test = local_data_dir % (test_num,) + "-nwpca"
mkdir(nwpca_dir_test)
if is_empty_folder(nwpca_dir_test):
	rsync(test_num)
	f.write("vision-auto-sta-64 " + local_data_dir % (test_num,) + " " + nwpca_dir_test + " " + movie_spec_test + " true true\n")
	f.write("echo 'test %d analyzed'\n\n" % (test_num,))

if transfer_set == 2:
	nwpca_dir_test = local_data_dir % (test_num+1,) + "-nwpca"
	mkdir(nwpca_dir_test)
	if is_empty_folder(nwpca_dir_test):
		rsync(test_num+1)
		f.write("vision-auto-sta-64 " + local_data_dir % (test_num+1,) + " " + nwpca_dir_test + " " + movie_spec_test + " true true\n")
		f.write("echo 'test %d analyzed'\n\n" % (test_num+1,))
	
	mapped_path = local_data_dir % (test_num+2,) + "-from-data%03d-nwpca" % (test_num+1,)
	mkdir(mapped_path)
	if is_empty_folder(mapped_path):
		mkdir(local_data_dir % (test_num+2,))
		rsync(test_num+2)
		f.write("map-auto " + local_data_dir % (test_num+2,) + " " + nwpca_dir_test + " " + mapped_path + " ei\n")
		f.write("echo 'data set %d mapped'\n\n" % (test_num+2,))
	

f.close()
st = os.stat(filename)
os.chmod(filename, st.st_mode | stat.S_IEXEC)